dist: trusty
language: ruby
rvm:
  - 2.5.0

sudo: false

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

install:
  - gem install html-proofer
  - bundle install
  - npm install -g gulp@3.9.1
  - npm install

before_script:
  - npm run build

script:
  - htmlproofer ./_site --check_favicon --check_html --disable-external
  - npm run lint

cache:
  directories:
    - ".bundle"
    - "node_modules"

branches:
  only:
    - master
    - /^feature.*$/
    - /^greenkeeper/.*$/
    - /^dependabot/.*$/
