# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      /blog/:year/:month/:day/:title/

# Pagination
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: 8
  permalink: /page/:num/
  title: ':title - page :num'

# Disqus
disqus:
  shortname: https-valerymelou-com

# Server
source:         "."
destination:    ./_site
host:           0.0.0.0
port:           9000
baseurl:        ""
url:            "https://valerymelou.com"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - .ruby-version
  - _assets/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
  - README.md

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-paginate-v2

# Social
title:              Valery Melou
description:        "Full-stack web developer from Yaounde, Cameroon."
twitter:            valerymelou
social_image_path:  /assets/images/brand/valery-social.png
social_logo_path:   /assets/images/brand/valery-social-logo.png

# Custom variables
